### PR TITLE
docs(samples): deleted quickstart file and corresponding test

### PR DESCRIPTION
**Pull request by Sita04**
Deleted the reCAPTCHA Quickstart file.
Quickstarts in reCAPTCHA are being revamped to a new workflow and this sample doesn't represent a quickstart.

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-recaptcha-enterprise/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Review by chingor13 — CHANGES_REQUESTED** [review]
Is there an internal bug for why this quickstart needs to be removed?

**Comment by Sita04** [comment]
> Is there an internal bug for why this quickstart needs to be removed?

Kindly refer to b/219389828#comment3

**Comment by sofisl** [comment]
@Sita04, would it be possible to fix the sample instead of removing it completely? It makes for a bad user experience to not see a quickstart.

**Comment by sofisl** [comment]
@Sita04, are you still planning on refactoring this sample to retag it? Friendly bump.

**Comment by sofisl** [comment]
@Sita04, would you mind renaming the file if it's not a quickstart, or else deleting it entirely if it's not a viable sample? Thank you.

**Comment by sofisl** [comment]
@Sita04, I think you also need to delete the corresponding test, and update the title. Thank you!

**Comment by Sita04** [comment]
> @Sita04, I think you also need to delete the corresponding test, and update the title. Thank you!

The test file contains only quickstart test. So, I removed the testcase and the folder too. Still, I get the missing test file error. Is it mandatory to have a testfile even though there are no testcases in it?

**Review by bcoe — APPROVED** [review]
I'm going ahead and approving and merging, based on the wishes of the product team, and since it sounds like the current quickstart is not useful 👍

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
